CREATE TABLE Files (
	file_id INT AUTO_INCREMENT PRIMARY KEY,
	file_name VARCHAR(255) NOT NULL,
	mime_type VARCHAR(100) NOT NULL,
	file_key VARCHAR(255) NOT NULL,
	file_url VARCHAR(255) NOT NULL
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);