CREATE TABLE countries (
	country_id INT AUTO_INCREMENT PRIMARY KEY,
	country_name VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);